### ISSUE TITLE
How can I show Docs instead of categories in homepage?

### ISSUE THREAD

**Issue by svcnt** [tareq1988/wedocs#24]
Thanks Tareq for your work.

I'm moving my documentation and project management site from MediaWiki to WordPress, and I'd like to use your weDocs theme. My homepage right now in the wiki looks a lot like your demo -> http://docs.wedevs.com/

But when I installed the theme, the homepage in my WordPress site showed post categories instead of docs. How can I remove categories and display docs nstead?

Thank you in advance.

**Comment by tareq1988** [comment]
I have [released a plugin](https://tareq.co/2016/03/wedocs-released-as-a-plugin/) last week based on the works of this theme. Right now docs.wedevs.com is the mix of this theme and the plugin. You can find the latest version of the theme in the develop branch. 

About project management, did you try my [project management plugin](https://wordpress.org/plugins/wedevs-project-manager/) yet? The plugin just got a huge UI improvements. The pro version has a lot of features (just sayin ;) ).

**Comment by svcnt** [comment]
Ooops!

I have installed the weDocs plugin in a multi-site wp, activate it just for my documentation sub-site and here's what I get -> "Plugin could not be activated because it triggered a fatal error."

BUT, if I change the theme from weDocs to any other, I can activate the plugin without problems.

Any ideas?

And yes, i'm also giving a try to WP Project Manager, thanks a lot.

**Comment by svcnt** [comment]
OK, I just activated the plugin sitewide and now everything works. 

I think this is going to help me a lot... Tank you.
