### ISSUE TITLE
show only grand children instead of with children

### ISSUE THREAD

**Issue by ufukayyildiz** [tareq1988/wedocs#40]
hi,

after click a wedocs link, it shows grand children with its children. is it possible to show only grand children, 

as on image.
![wedocs](https://cloud.githubusercontent.com/assets/23309320/22687244/e13294ac-ed2f-11e6-8d5d-73f6d7dee140.png)

thank you.

**Comment by shumbo** [comment]
@atozsoft Hi. That article list is generated by 

https://github.com/tareq1988/wedocs/blob/develop/templates/content-single.php#L21

this line. You can provide `depth` property to limit the depth they query. Probably, what you want to do is to change this line like this.

```php
$children = wp_list_pages("title_li=&order=menu_order&depth=1&child_of=". $post->ID ."&echo=0&post_type=" . $post->post_type);
```

By adding `depth=1`, that would displays only the posts directly belongs to the current post.

I hope my understanding of your question is correct and this can help you. Thanks,

**Comment by ufukayyildiz** [comment]
@shumbo hi,

thank you. this is exactly what i want. fixed my problem. so thanks.
