### ISSUE TITLE
Change url

### ISSUE THREAD

**Issue by korud** [tareq1988/wedocs#46]
Hello, I want to congratulate you for this great plugin, for me the best documentation plugin, the only problem is that you are missing some options. I can adapt it well to my website, but I would like to change the url. Currently my blog url is www.example.com/blog/docs and I would like to put it on www.example.com/docs or www.example.com/projects. Can you help me with this?

**Comment by korud** [comment]
Hi, for change the name of section in wedocs.php
`$rewrite = array(
            'slug'                => 'docs',
            'with_front'          => true,
            'pages'               => true,
            'feeds'               => true,`
change word docs by your like.  Next is necesary update permalinks in settings wordpress.
I would like use the section docs in the root url.

**Comment by korud** [comment]
Ok, It is ok. for change the url if it is in subfolder for example
example.com/blog/docs and you prefer in root example.com/docs in wedocs.php:
`$rewrite = array( 'slug' => 'docs', 'with_front' => true, 'pages' => true, 'feeds' => true,`
change:
`'with_front' => true,` 
to false:
`'with_front' => false,` 
Next is necesary update permalinks in settings wordpress.

**Comment by Stiofan** [comment]
For anyone else readin this i also had to change 'slug' => 'docs' to 'slug' => '/'

**Comment by rosangelamAVI** [comment]
I need to do something similar as well. I currently have this development site: https://devkompar.wpengine.com/docs/why-use-static-analysis/ and I'd like to change the "/docs/" in the url to be "/resources/".
Within the 1.6.2 version of wedocs.php - Do I need to add the above mentioned "rewrite" code to the file of wedocs.php or is there a certain other file I can go into to change it?
